mediachain/aleph

src/client/api/RestClient.js, src/client/cli/commands/query.js
adds a new `query` command that accepts a query string and sends it over the HTTP api.
also cleans up the awkward promise handling in RestClient
=> Query command, better promise handling

CONTRIBUTING.md, README.md
Adds some install, usage, and development instructions to the README.
closes #28 
TODO:
=> Fill in README

.gitignore, scripts/dataset-fetch.py, scripts/ingest-parallel.py, scripts/publish-500px.sh, scripts/publish-dpla.sh, scripts/publish-flickr.sh, scripts/publish-pexels.sh, src/client/cli/commands/publish.js
- modify ingest-parallel to spawn as many workers as cpus by default.
- add publish scripts for ingesting our datasets
- publish-dpla.sh for DPLA
- add a dataset-fetch script to download (parts of) a dataset starting from a manifest file, and batch it for execution by ingestion workers.
- fix leftover debugging prints in publish.js
TBD: scripts for our other seed datasets
=> Ingestion scripts

README.md, integration-test/index.js, integration-test/util.js, src/client/api/RestClient.js, src/client/cli/commands/config/dir.js, src/client/cli/commands/config/info.js, src/client/cli/commands/config/nat.js, src/client/cli/commands/getData.js, src/client/cli/commands/id.js, src/client/cli/commands/listPeers.js, src/client/cli/commands/merge.js, src/client/cli/commands/ping.js, src/client/cli/commands/publish.js, src/client/cli/commands/publishRaw.js, src/client/cli/commands/putData.js, src/client/cli/commands/query.js, src/client/cli/commands/statement.js, src/client/cli/commands/status.js, src/client/cli/index.js
Adds some features that were recently added to concat
- `listPeers` command to get list of peers from node's connected directory
- fetch ids and info from remote peers, format output instead of dumping JSON
- update mcclient query command to support remote query
- add merge command
- get / set peer's info message
- get / set NAT config
- rename cli flags a bit (`--peerUrl` is now `--apiUrl`)
=> Update client with missing concat functionality

src/client/cli/commands/listPeers.js
```
mcclient listPeers --info
QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ -- Metadata for CC images from DPLA, 500px, and pexels; operated by Mediachain Labs.
QmZ6dckUhRouVr6AsBTpK6vMLVpcz1KAeJAJVQEZQ5gCek -- Metadata for CC images from flickr; operated by Mediachain Labs.
```
If an info lookup fails, it will print `Unable to fetch info: ${err.message}`, but won't fail the whole command.
=> Add --info flag to listPeers command to fetch info strings

src/client/cli/commands/publish.js
Closes #50 
This just adds a `.toString` on the selected id, after making sure it isn't null.
Also, moves the `.catch` to the correct place where it result in a misleading "All statement published successfully" message even when an error occurs.
=> Fix publish error when id is not a string, remove lying "success" message

src/client/cli/commands/config.js, src/client/cli/commands/publishSchema.js, src/client/cli/index.js
Enables strict mode for yargs option parser, so we print usage text and error out on unknown arguments / commands.
Also wraps the help text at the actual terminal width, instead of 80 columns, and fixes up the help text for the publishSchema command for consistency with the rest.
=> CLI option parsing tweaks

scripts/build-jq.js, src/client/cli/commands/publish.js
Closes #63 
Moves the `toString` call on the id into javascript instead of putting it in the jq filter, so that `null` doesn't get transformed into `"null"`.
=> Throw error if idFilter returns null

docs/schema-generation.md, package.json, src/metadata/schema.js, src/metadata/schemas/com.snowplowanalytics.self-desc-jsonschema-1-0-0.json, test/schema_test.js
This makes the `publishSchema` command compatible with schemas generated with the [schema-guru](https://github.com/snowplow/schema-guru) tool, and adds `docs/schema-generation.md` to explain how to generate a schema and use it when publishing records, using MoMA artworks as an example.
I'd like to eventually automate the schema generation by wrapping schema-guru, but this works pretty well for now.
=> Compatibility with schema-guru generated schemas

src/client/cli/commands/getData.js, src/client/cli/commands/query.js, src/client/cli/commands/statement.js, src/client/cli/util.js
Pipes json through jq for pretty printing instead of using `console.dir`, so we get valid json output with quotes and such.
Defaults to printing in color if stdout is a TTY, but you can override with `prettyPrint(obj, {color: false})`
Will add the flag for pretty printing per @vyzo's suggestion; do we want it to be enabled or disabled by default?  Pretty output by default seems nicer for end users... @denisnazarov, thoughts?
closes #64
=> Use jq for pretty printing

.travis.yml, README.md
Similar to the concat release process, this should let us just tag a release with a tag beginning with `v`, and it will publish to npm for us.
also adds an npm version badge to the readme, which I've been meaning to do for a while 😄
=> Deploy to npm on commits tagged with `v*`

package.json, src/metadata/serialize.js
This prevents the cbor encoder from choking on objects larger than 16KB.  I set the new limit at 1MB, so hopefully that's enough for everybody 😄
=> Increase input size limit for cbor encoder

src/client/api/RestClient.js, src/client/cli/commands/listPeers.js
This adds a default 15s timeout to all `RestClient` requests.  You can override the default by providing a `requestTimeout` to the constructor options when creating the `RestClient`.  Long-running requests (big queries, etc) aren't affected by the timeout, just cases where no data is received within the limit.
Also changes the behavior of the `listPeers -i` command to print the peer id and info string as soon as the info request completes, rather than waiting for all requests to complete.  This means that reachable nodes are immediately shown, and there's a delay for unreachable nodes before an error is printed.
=> Timeouts for mcclient requests, better behavior for `listPeers -i`

src/peer/libp2p_node.js, src/peer/util.js, test/ping_test.js
This adds a 10s timeout when dialing using libp2p, and also fixes the `pullToPromise` helper, which was ignoring errors instead of rejecting the promise.
This should fix the broken behavior in the aleph repl where it would eventually return `true` when pinging an unreachable node.
You can change the timeout length on a mediachain node after construction by doing `node.p2p.dialTimeout = newValue`.  It might be worth adding the timeout duration as an argument to the MediachainNode class constructor though; right now it's just in the P2PNode class.
=> Dial timeouts for p2p connections

npm-shrinkwrap.json
The node-webcrypto guys seem to have [fixed the install issue](https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/75), so this just updates our shrinkwrap file to use the latest version of node-webcrypto-ossl.  I think it's probably still a good idea to use shrinkwrap, since it'll hopefully let us avoid things like this in the future.  The only downside is that it makes it a bit trickier for people to use aleph as a library (since they might need non-shrinkwrapped versions of things we depend on), but we can revisit if people start doing that 😄
=> Update to fixed version of node-webcrypto-ossl

integration-test/node_info_test.js, integration-test/util.js, src/peer/constants.js, src/peer/node.js, src/protobuf/index.js, test/node_info_test.js
Adds a `remoteNodeInfo` method to `MediachainNode` that retrieves the ids and info message.  Also adds an `idHandler` to provide the same, although the publisher id is blank since aleph doesn't support them yet.  I did add an `infoMessage` to the node constructor, so you can set the info string.
A thought I had when adding that `infoMessage` parameter is that it won't persist between invocations... maybe it's worth adding a way to save the node configuration (id, info, directory address, etc) to a single JSON file?
=> Support /mediachain/node/id protocol

src/peer/identity.js, src/peer/libp2p_node.js, src/peer/node.js, src/peer/repl/commands/repl.js
Also makes `peerInfo` mandatory in the MediachainNode constructor options, and reworks a few things in the repl command to please our new async overlords.
=> Use async PeerId API

src/client/cli/commands/validate.js, src/metadata/schemas/io.mediachain.jsonld-jsonschema-1-0-0.json
This adds a jsonschema for structurally validating JSON-LD objects, and adds a `--jsonld` flag to the `mcclient validate` subcommand.  It also changes the `schema` argument for that command to be hyphenated (`--schema`) instead of a positional argument, and it's now mutually exclusive with `--jsonld`.  Running with `--jsonld` is equivalent to `--schema <pathToJsonldSchema>`
I haven't wired this up to the `publish` command yet, because to do it right we have to ensure that the jsonld schema has been published to the node before we publish the records.  That's certainly doable, but I just haven't implemented it yet.
=> Add structural jsonld validation to `mcclient validate`

scripts/build-jq.js, src/metadata/jqStream.js
This fixes the install error described in #97, where jq would fail because we were trying to copy to a non-existent directory.  I changed the jq install dir to `<aleph-root>/bin/jq` instead of trying to put it in the `node_modules/.bin`.  I expect vyzo's "I told you so" on my desk Monday morning 😛.  I also tossed a `mkdirp` in before the build step to ensure the directory exists.
=> Change jq install location, ensure directory exists

package.json, src/client/api/index.js, src/client/cli/commands/auth/grant.js, src/client/cli/commands/auth/revoke.js, src/client/cli/commands/auth/show.js, src/client/cli/commands/config/dir.js, src/client/cli/commands/config/info.js, src/client/cli/commands/config/nat.js, src/client/cli/commands/delete.js, src/client/cli/commands/getData.js, src/client/cli/commands/id.js, src/client/cli/commands/listPeers.js, src/client/cli/commands/merge.js, src/client/cli/commands/netAddr.js, src/client/cli/commands/ping.js, src/client/cli/commands/publish.js, src/client/cli/commands/publishRaw.js, src/client/cli/commands/publishSchema.js, src/client/cli/commands/push.js, src/client/cli/commands/putData.js, src/client/cli/commands/query.js, src/client/cli/commands/shutdown.js, src/client/cli/commands/statement.js, src/client/cli/commands/status.js, src/client/cli/commands/validate.js, src/client/cli/index.js, src/client/cli/util.js
This adds a `--deployCredentialsFile` option that you can point at the file downloaded at the end of the Deploy process.  If given, it will create an SSH tunnel for you to the remote machine, using the ip address, username and password from the file. It uses a javascript SSH implementation, so it should work on Windows.
To get this to work, I made a `subcommand` helper function that wraps each subcommand handler.  If an SSH config is given, it creates the tunnel, runs the handler, then closes the tunnel afterwards.  The subcommand handler functions had to be tweaked slightly to return a `Promise`, which the wrapper waits on before closing the tunnel.
I also made the `subcommand` helper create the `RestClient` instance, so subcommands can just pull the `client` member out of their options …
=> Automatic SSH tunneling with Deploy credentials file

src/client/api/RestClient.js, src/client/cli/commands/data.js, src/client/cli/commands/data/compact.js, src/client/cli/commands/data/gc.js, src/client/cli/commands/data/get.js, src/client/cli/commands/data/keys.js, src/client/cli/commands/data/put.js, src/client/cli/commands/data/sync.js, src/client/cli/commands/getData.js, src/client/cli/commands/putData.js
This adds some new commands to support the new endpoints added in https://github.com/mediachain/concat/pull/88
- `mcclient data gc`
- `mcclient data compact`
- `mcclient data sync`
- `mcclient data keys`
It also moves `getData` and `putData` to `mcclient data get` and `mcclient data put`, but keeps the old commands around as aliases.  Now that we have a bunch of datastore commands it seemed appropriate to group them.
@vyzo let me know if I'm missing anything.  I remember you saying something about making sync a flag on the gc command?  But my memory is fuzzy enough that I figured I'd wait till tomorrow and you can set me straight.
=> mcclient support for GC endpoints

src/client/api/RestClient.js, src/client/cli/commands/lookupPeer.js, src/client/cli/commands/ping.js
This adds the `/net/lookup/:peerId` endpoint to `RestClient` and a `lookupPeer` cli command that uses it.
Depends on https://github.com/mediachain/concat/pull/90
=> Add lookupPeer command & net/lookup api support

package.json, scripts/build-jq.js
This adds a step to `build-jq.js` that first tries to download the precompiled binary for jq for the platform it's running on, falling back to building it if there isn't one, or if the download fails.
Makes the installation speedier, and also makes it possible to install aleph on "real" windows, now that node-webcrypto-ossl is an optional dependency. (although you still need a C++ compiler setup for the sha3 module).
TODO:
=> Try to fetch precompiled jq, fall back to building

integration-test/concat-dependencies/Dockerfile
This updates the concat-dependencies Dockerfile:
- update go base image 1.7.3 from 1.7.1
- use standard setup.sh script
Since this is based on the latest master, it gets the most recent gx dependencies.  It's already pushed to Docker hub, and I removed the Travis environment variable that skips the integration tests, so this seems to have fixed up our CI mess.
=> Update concat-dependencies Dockerfile

src/client/cli/commands/publish.js
While working on some docs for publishing with json schema, I noticed that we weren't actually throwing validation errors for invalid records 😞 
This was caused by forgetting to actually return the schema object.  Anyway, this fixes that, and also  fixes the error handling so that errors call `reject` instead of throwing, so we just print the error message instead of the full stack trace.
=> Fix for records not actually being validated during publish

src/client/api/RestClient.js, src/client/cli/commands/netAddr.js, src/client/cli/commands/netConnections.js
Brings mcclient up to date with https://github.com/mediachain/concat/pull/97
Adds the `mcclient netConnections` command to list active connections, and an optional `peerId` argument to `mcclient netAddr` to show known addresses.
Also does a bit of refactoring to the response parsing code in RestClient, since I was getting tired of repeating the same string splitting and number parsing code for each new endpoint.
=> Add net/conn and net/addr/:peerId support to mcclient

npm-shrinkwrap.json, package.json, src/client/api/RestClient.js, src/client/cli/commands/data/get.js, src/client/cli/commands/getData.js, src/client/cli/util.js
Adds support for the batch get support added in https://github.com/mediachain/concat/pull/100
The `mcclient data get` command now accepts multiple keys and will fetch them with the batch interface.
Right now it prints the returned objects directly to the console one after another; I'm torn on whether we should wrap them in an array literal first, so that the entire output would be valid JSON.
=> Batch data object fetching for mcclient

src/client/cli/index.js, src/client/cli/util.js
This adds a new global `--timeout` argument to set the timeout (in seconds) for requests to the mcnode api.  
Thanks to the `subcommand` helper I made earlier, I only had to change two files, so that's nice :)
=> Add global `--timeout` flag to set request timeout

src/client/api/RestClient.js, src/client/cli/commands/listNamespaces.js, src/client/cli/commands/listPeers.js, src/peer/constants.js, src/protobuf/dir.proto, src/protobuf/index.js, src/protobuf/types.js
Adds support for https://github.com/mediachain/concat/pull/101
- Adds `mcclient listNamespaces`
<details>
<summary> list namespaces example</summary>
```
$ mcclient listNamespaces
images.500px
images.dpla
images.flickr
images.pexels
mediachain.schemas
museums.brooklynmuseum.artists
museums.brooklynmuseum.collections
museums.brooklynmuseum.exhibitions
museums.brooklynmuseum.geographicallocations
museums.brooklynmuseum.museumlocations
museums.brooklynmuseum.objects
museums.cooperhewitt.objects
museums.moma.artists
museums.moma.artworks
museums.rijksmuseum.artworks
museums.tate.artists
museums.tate.artworks
```
</details>
- Adds `namespace` argument to `mcclient listPeers` to return peers that publish to given namespace:
```
$ mcclient listPeers --info 'images.500px' …
```
=> mcclient support for namespace listings

npm-shrinkwrap.json, package.json, src/metadata/serialize.js
This swaps out the `cbor` module with [`borc`](https://github.com/dignifiedquire/borc), @dignifiedquire's awesome fast cbor codec.
A quick test publishing MoMA artworks show almost 2x real-world improvement:
```
$ time mcclient publish --idFilter .ObjectID --namespace scratch.moma Artworks.ndjson >/dev/null
27.13 real        29.31 user         1.00 sys
$ time mcclient publish --idFilter .ObjectID --namespace scratch.moma Artworks.ndjson >/dev/null
50.52 real        52.37 user         1.53 sys
```
=> Use borc module for fast cbor conversion

src/client/cli/commands/auth/grant.js, src/client/cli/commands/auth/revoke.js, src/client/cli/commands/config/dir.js, src/client/cli/commands/config/info.js, src/client/cli/commands/config/nat.js, src/client/cli/commands/data/compact.js, src/client/cli/commands/data/gc.js, src/client/cli/commands/data/keys.js, src/client/cli/commands/data/put.js, src/client/cli/commands/data/sync.js, src/client/cli/commands/delete.js, src/client/cli/commands/id.js, src/client/cli/commands/listNamespaces.js, src/client/cli/commands/listPeers.js, src/client/cli/commands/lookupPeer.js, src/client/cli/commands/merge.js, src/client/cli/commands/netAddr.js, src/client/cli/commands/netConnections.js, src/client/cli/commands/ping.js, src/client/cli/commands/publish.js, src/client/cli/commands/publishRaw.js, src/client/cli/commands/publishSchema.js, src/client/cli/commands/push.js, src/client/cli/commands/shutdown.js, src/client/cli/commands/status.js, src/client/cli/commands/validate.js, src/client/cli/util.js
It turns out that [console.log retains its arguments indefinitely](http://stackoverflow.com/a/13001962) and prevents them from being GC'd, so you can do fancy things with them like inspect them in dev tools.
This was causing us to eventually run out of heap space when publishing millions of records, since I was using `console.log` to output the statment ids, etc.
This adds a `println` utility function that calls `process.stdout.write`, and replaces all the `console.log`s with `println`. A lot of the console.logs wouldn't matter, since they're in one-off commands like `mcclient id`, but I kind of wanted to burn them all to the ground after chasing this leak all day 😄
There's a few other changes to the publish command:
- instead of accumulating all promises for each batch publication and …
=> Fix memory leak in publish command

integration-test/util.js, src/client/api/RestClient.js, src/client/cli/commands/config/dir.js
`mcclient config dir` now accepts multiple directory addresses, and the `RestClient` methods have had their names and type signatures updated to support multiple directories.
=> Allow getting/setting multiple directory servers

src/client/cli/util.js
This changes the SSH tunnel setup to bind to any available port, and rewrites the `apiUrl` to use the bound port before passing the `RestClient` to the subcommand worker functions.
This lets you tunnel to a remote node while a local node is bound to the default port, or run multiple tunneled commands in parallel.
It also removes the requirement that the `sshConfig` have either a `password` or `privateKey` field, which makes the tunnel lib fallback to using ssh-agent to authenticate.
=> Bind SSH tunnel to any open port

src/client/api/RestClient.js, src/client/cli/index.js, src/client/cli/util.js
Per conversation with @vyzo in slack, the global request timeouts were causing a lot of problems for operations that take awhile to finish (e.g. publish, etc).
We talked about removing the global timeout and making certain operations opt-in, for example fetching the remote id for a peer.  I started to do that, but I couldn't come up with a compelling reason to keep the timeouts at all, versus just passing on the error from concat when its timeouts are exceeded.
With timeouts on the `mcclient` -> `mcnode` http connection, you get a confusing error message, and you may end up timing out before `mcnode` would have given you a more useful message.  I'm now thinking that if we're going to have a timeout parameter, it should be sent as part of the HTTP request (e.g in a query param), so that …
=> Change default timeout to none

src/peer/identity.js, test/signature_test.js
This is pretty barebones, but shows how to sign and verify with a PublisherId (which is just a wrapper around a libp2p-crypto PrivateKey).
I've got a couple mediachain statement specific verification methods on my merge branch; I'll add tests for those soon.
=> Basic test of signing / verifying buffers

npm-shrinkwrap.json, package.json, src/client/api/RestClient.js, src/client/cli/commands/net.js, src/client/cli/commands/net/addr.js, src/client/cli/commands/net/connections.js, src/client/cli/commands/net/identify.js, src/client/cli/commands/net/ping.js, src/client/cli/commands/netAddr.js, src/client/cli/commands/netConnections.js, src/client/cli/commands/ping.js, src/peer/libp2p_node.js, src/peer/node.js, test/ping_test.js
This adds mcclient `net ping` and `net identify` commands to support the new endpoints added in https://github.com/mediachain/concat/pull/113
I also moved `netAddr` and `netConnections` to `net addr` and `net connections`, but left the old commands as aliases.
Aleph nodes now support the libp2p-ping protocol, and will try to use it when pinging remote nodes, falling back to the `/mediachain/node/ping` protocol if the libp2p-ping fails.
I didn't add an equivalent of `net identify` to aleph nodes; we should be able to do so without too much fuss if we end up needing it.  We do support the identify protocol as part of the libp2p-swarm setup, so a concat node should be able to get some info from us, although the js implementation of libp2p-identify doesn't populate the `protocols` field, …
=> More ipfs interop

src/client/cli/commands/publish.js, src/peer/node.js, test/merge_test.js, test/remote_query_test.js, test/util.js
This add a basic aleph-only test for the merge functionality by mocking the query protocol on an aleph node and merging from it.
I uncovered what looks like a bug in js-libp2p; if you try to open two connections in parallel to the same javascript peer, you get 
```
Uncaught Error: incorrect header check
at Zlib._handle.onerror (zlib.js:370:17)
```
Changing the connection code in `MediachainNode.merge` from using `Promise.all` to open the streams in parallel to using `.then` to only open the second stream after the first stream is opened makes the error go away... 
I'm not sure what the root cause of the error is; possibly something in the stream multiplexing code.
=> Add test for aleph merge, fix connection bug

npm-shrinkwrap.json, package.json, src/peer/db/statement-db.js
It seems that knex's connection pool doesn't like in-memory sqlite databases.  It's configured to release a connection after an idle timeout, but reopening a connection to `:memory:` creates a new, empty database.  The result is that our unit tests all pass, since they complete before the 30 second timeout, but actually trying to use the db at the repl results in your data getting erased (unless you're an especially fast typist 😄)
This just creates a temporary file with the `node-temp` module and uses it instead of `:memory:`.  I set up node-temp to track and remove temp files at process exit, so we shouldn't be cluttering up the temp directory.
=> Use temp file for statement db to avoid connection timeout issues

src/client/api/RestClient.js, src/client/cli/commands/manifest/lookup.js, src/protobuf/dir.proto, src/protobuf/index.js, src/protobuf/node.proto, src/protobuf/types.js
This adds a command for the `/dir/listmf/:entityId` API endpoint added in https://github.com/mediachain/concat/pull/125
`mcclient manifest list blockstack:vyzobot.id` should give you this if you're running `mcnode` from master: 
```
[
{
"entity": "blockstack:vyzobot.id",
"keyId": "Qmcvnd3Jn41DwSjaZcVXpTpX873czeSAAf3PcyyULdvFZc",
"body": {
"node": {
"peer": "QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ",
"publisher": "4XTTM4K8sqTb7xYviJJcRDJ5W6TpQxMoJ7GtBstTALgh5wzGm"
}
},
"timestamp": "1485367315",
"signature": "KB9tExh+kUNuAEhlm0qXhgSIAhYWP+zABnVR3pRk+cUFFsAO0rOknm3sO+zP2n+ysDvS88JiZbeuENhdzEcHBQ=="
},
{
"entity": "blockstack:vyzobot.id",
"keyId": "Qmcvnd3Jn41DwSjaZcVXpTpX873czeSAAf3PcyyULdvFZc",
"body": {
"node": {
"peer": "QmZ6dckUhRouVr6AsBTpK6vMLVpcz1KAeJAJVQEZQ5gCek",
"publisher": …
```
=> Add `mcclient manifest lookup` command

integration-test/push_test.js, src/model/statement.js, src/peer/merge.js, src/peer/node.js, src/protobuf/types.js, test/metadata/signature_test.js, test/model/statement_test.js, test/peer/merge_test.js, test/peer/push_test.js
This refactors the Statement class hierarchy a bit to make a clean split between signed and unsigned statements.
There's now a base `Statement` class that has everything except the `signature` field, plus common helper methods like `.toProtobuf`, `.expandObjects`, etc.
The `UnsignedStatement` subclass adds the `.calculateSignature` and `.sign` methods, which return `Buffer` and `SignedStatement`, respectively.
The `SignedStatement` class has the `signature` field and the `.verifySignature` method.  Both `SignedStatement` and `UnsignedStatement` inherit from `Statement` directly, so `SignedStatement` does not have the `.sign` and `.calculateSignature` methods.  However, there's a helper on the the base class `.asUnsignedStatement()` that will return an unsigned copy of either a signed or …
=> Define separate SignedStatement & UnsignedStatement classes

npm-shrinkwrap.json, package.json, src/common/util.js, src/peer/datastore.js
Since the synchronous `multihashing` module is [no longer recommended](https://github.com/multiformats/js-multihashing/issues/18#issuecomment-278742801), this removes our dependency on it.
We're were using it in the `b58MultihashForBuffer` helper (and `Datastore.put` which was written before the helper and can use it instead).
We are calling that helper in a couple of sync methods (like the constructor for `ExpandedSimpleStatementBody`), so I did the lazy thing and just did a synchronous implementation using node's `crypto.createHash` instead of trying to make everything async so we can use https://github.com/multiformats/js-multihashing-async which uses `crypto.createHash` on node anyway.
=> Remove dependency on multihashing module

npm-shrinkwrap.json, package.json, src/client/api/RestClient.js, src/client/cli/commands/archive.js, src/model/statement.js, test/model/statement_test.js, test/resources/fixtures/test-statements.js
I figured that it would be easier to just make the tarball in JS using the [tar-stream](https://github.com/mafintosh/tar-stream) module vs writing some shell or python scripts, since we already have the code to extract and request the associated objects.
This adds an `mcclient archive <queryString>` command that will write a gzipped tarball to stdout (or you can give a `--output|-o` flag).  In the tarball will be a `stmt/<statementId>` entry for each statement, and a `data/<objectId>` entry for each data object.  The statements are stringified JSON objects, but could easily do protobufs instead.
Happy to tweak the archive format in the morning (multiple statements per entry is probably a good idea).
=> Add `mcclient archive` command to generate archive tarball

npm-shrinkwrap.json, src/model/statement.js, src/peer/repl/commands/query.js, src/peer/repl/commands/repl.js, test/model/statement_test.js
I noticed on Friday that the recent Statement class refactor in #177 broke the output of the `aleph query` command if you use it with the `--includeData` flag.  The "expanded" object body is included when you call `inspect`, but not when you try to print the `Statement` object as JSON. 
So this PR changes the way we override the depth of the `inspect` call.  Instead of doing it in the `Statement.inspect` method, we just return the JS object we want to print from `Statement.inspect`, and override the default inspect depth in the repl command.  That way, in the `aleph query` command, we can call `.inspect()` on the query result and print it, including the embedded object.
This is much cleaner anyway, since how you format the output shouldn't be tied to the Statement class.  I think when I …
=> Fix output for `aleph query --includeData`
